import type { IPublicClientApplication } from "@azure/msal-browser";
import createFetchClient, { type Middleware } from "openapi-fetch";
import createClient from "openapi-react-query";
import type { paths } from "./schema"; // generated by openapi-typescript
import { authRequest } from "@/auth/config";

export type ApiClient = ReturnType<typeof createApiClient>;

export function createApiClient(msalInstance: IPublicClientApplication) {
  const authMiddleware: Middleware = {
    async onRequest({ request }) {
      const activeAccount = msalInstance.getActiveAccount();
      const accounts = msalInstance.getAllAccounts();
      const account = activeAccount || accounts[0];

      const authResult = await msalInstance.acquireTokenSilent({ ...authRequest, account });

      request.headers.set("Authorization", `Bearer ${authResult.accessToken}`);

      return request;
    },
  };

  const fetchClient = createFetchClient<paths>({
    baseUrl: "/",
  });

  fetchClient.use(authMiddleware);

  const reactQueryClient = createClient(fetchClient);

  return reactQueryClient;
}